### ISSUE TITLE
Clone Homebrew julia deps bottles regularly

### ISSUE THREAD

**Issue by staticfloat** [staticfloat/julia-buildbot#13]
See [original comment](https://github.com/JuliaLang/julia/pull/9581#issuecomment-68627422), essentially we need to loop over `brew deps --HEAD julia`, call `brew fetch --force-bottle $dep`, parse the output for downloaded bottle, ensure that bottle is uploaded to AWS, if not, upload the new one.

For parsing out downloaded location, this seems to work well:
```
$ brew fetch --force-bottle gcc | grep -i downloaded | cut -d-f2- | xargs echo
/Library/Caches/Homebrew/gcc-4.9.2_1.yosemite.bottle.tar.gz
```

To download bottles of different platforms, we can parse out download URL and replace it with our own new platforms:
```
$ brew fetch --force-bottle gcc | grep Downloading | awk '{ print $3 }' | sed -e "s/yosemite/mountain_lion/"
https://downloads.sf.net/project/machomebrew/Bottles/gcc-4.9.2_1.mountain_lion.bottle.tar.gz
```

To figure out what bottles need to be uploaded, we can just `[[ -z "$(aws ls bucketname -l | grep bottle_filename)" ]]`.

**Comment by tkelman** [comment]
`brew deps --HEAD julia`

**Comment by staticfloat** [comment]
:+1:

**Comment by staticfloat** [comment]
Ref https://github.com/Homebrew/homebrew/issues/35586

**Comment by staticfloat** [comment]
Not doing this since we now have the caching server.
