### ISSUE TITLE
Build bot not using julia-nightlies.spec from master?

### ISSUE THREAD

**Issue by nalimilan** [staticfloat/julia-buildbot#14]
Fedora Copr maintainers have notified me that the Julia nightlies were constantly failing for about a week. And indeed it looks like my last commit on master (83f069cc3ad3c1dbe30a0996652eb3f074f9c051) isn't taken into account when building the SRPMs. If you look e.g. at the end of this file, you can see that the list of tests I removed in the commit is still present:
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-21-x86_64/julia-0.4.0-0.20150116.el7.centos/build.log

Any idea where this might come from?

**Comment by staticfloat** [comment]
Sorry I missed this.  Is this still an issue?

**Comment by nalimilan** [comment]
Looks like it's gone. Not sure what may have happened. Is there a delay for the bot to use the new commits?

**Comment by staticfloat** [comment]
Ah, It doesn't pull down the latest git repository automatically.  I'll add
a cron job to do that.
-E

**Comment by nalimilan** [comment]
Thanks. BTW, do you think there could be a way to avoid running the builds more than once a day on Copr? I'm a bit concerned with the load we impose on their servers.

**Comment by staticfloat** [comment]
Sure, I'll change it to only run once every 24 hours.

**Comment by nalimilan** [comment]
Cool!

**Comment by nalimilan** [comment]
Looks like the cron job is still running many times a day, and the Copr maintainers complained about it again. Can you fix that?

**Comment by staticfloat** [comment]
(hopefully) fixed in cde999adf6c759481bf5d6201c86caa0342f78a2

**Comment by nalimilan** [comment]
Thanks, I'll tell you. But I don't think it was run every hour, it would have created much more activity.

**Comment by staticfloat** [comment]
It was only run if there was a change, so it was running about once every
3-4 hours.  You can see the activity here
<http://buildbot.e.ip.saba.us:8010/builders/package_srpm>.
-E

**Comment by nalimilan** [comment]
Ah, that explains everything.
