### ISSUE TITLE
Kick the osx builders?

### ISSUE THREAD

**Issue by tkelman** [staticfloat/julia-buildbot#27]
http://buildbot.e.ip.saba.us:8010/builders

This has been delaying nightlies for about 3 days and will need addressing before we can make RC binaries. We can maybe manually work around it for all platforms other than mac if needed.

cc @staticfloat

**Comment by staticfloat** [comment]
Done.  The VM host got rebooted, but the VM didn't get started back up correctly.

**Comment by tkelman** [comment]
Thanks! I swear I've been trying things on rundeck before opening these, but so far with little success.

**Comment by staticfloat** [comment]
Yeah, unfortunately that problem wasn't solvable with rundeck.  :P
-E
