### ISSUE TITLE
New Windows builder fails

### ISSUE THREAD

**Issue by staticfloat** [staticfloat/julia-buildbot#32]
Hey @tkelman I'm a little stumped on this one.  I'm in the process of rebuilding the Windows buildbots (rather than jumping through all the hoops in the `julia-vagrant` repo to create a VM image, then uploading that image to OpenStack, I'm instead starting with whatever default windows image the VM provider we're currently using has, and then adding the necessary packages on using powershell scripts which were inspired by you) and I'm running into a bizarre problem with cygwin's `cmake`.

The first time I tried anything, I got a rather mysterious error which I then traced down to the fact that `cmake` was being invoked as `/bin/cmake` and not `/usr/bin/cmake`:
```
cd libgit2/build/ && \
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/home/Administrator/buildbot/slave/package_win6_2-x64/build/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_COMPILER="x86_64-w64-mingw32-gcc" -DCMAKE_C_COMPILER_ARG1="-m64 " -DCMAKE_CXX_COMPILER="x86_64-w64-mingw32-g++" -DCMAKE_CXX_COMPILER_ARG1="-m64 " -DTHREADSAFE=ON -DWIN32=ON -DMINGW=ON -DUSE_SSH=OFF -DCMAKE_SYSTEM_NAME=Windows -DBUILD_CLAR=OFF -DCMAKE_RC_COMPILER=`which x86_64-w64-mingw32-windres` -DDLLTOOL=`which x86_64-w64-mingw32-dlltool` -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32 -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
Makefile:1961: recipe for target 'libgit2/build/Makefile' failed
make[1]: Leaving directory '/home/Administrator/buildbot/slave/package_win6_2-x64/build/deps'
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
//share/cmake-3.3.1
CMake Error: Error executing cmake::LoadCache(). Aborting.

make[1]: *** [libgit2/build/Makefile] Error 1
Makefile:51: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
```
[Full log](http://buildbot.e.ip.saba.us:8010/builders/package_win6.2-x64/builds/0/steps/make/logs/stdio).

I then attempted to change the `PATH` (you can always see the current environment in blue text at the top of every buildbot step) and now it seems that the shell can't find `cmake` at all.
```
cd libgit2/build/ && \
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/home/Administrator/buildbot/slave/package_win6_2-x64/build/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_COMPILER="x86_64-w64-mingw32-gcc" -DCMAKE_C_COMPILER_ARG1="-m64 " -DCMAKE_CXX_COMPILER="x86_64-w64-mingw32-g++" -DCMAKE_CXX_COMPILER_ARG1="-m64 " -DTHREADSAFE=ON -DWIN32=ON -DMINGW=ON -DUSE_SSH=OFF -DCMAKE_SYSTEM_NAME=Windows -DBUILD_CLAR=OFF -DCMAKE_RC_COMPILER=`which x86_64-w64-mingw32-windres` -DDLLTOOL=`which x86_64-w64-mingw32-dlltool` -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32 -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
Makefile:1961: recipe for target 'libgit2/build/Makefile' failed
make[1]: Leaving directory '/home/Administrator/buildbot/slave/package_win6_2-x64/build/deps'
Makefile:51: recipe for target 'julia-deps' failed
/bin/sh: line 1: cmake: command not found
make[1]: *** [libgit2/build/Makefile] Error 127
make: *** [julia-deps] Error 2
```
[Full log](http://buildbot.e.ip.saba.us:8010/builders/package_win6.2-x64/builds/4/steps/make/logs/stdio).

If I login via SSH, I can invoke `cmake` just fine.  Is there anything particularly special about `cygwin` that I might be missing here?

**Comment by tkelman** [comment]
I'd say "maybe we should report this to the cygwin cmake maintainer" if that weren't me.

How are you starting cygwin?

**Comment by staticfloat** [comment]
So far it's always been my logging in via SSH; I've got an SSH server running as a service, using [this script](https://gist.github.com/staticfloat/9c93f74acb9f8e67bfd9).  Should I try it by just opening a cygwin terminal on the machine over RDP?

**Comment by tkelman** [comment]
It's worth trying. There might be some mounting or other bashrc type commands that would normally get run but aren't happening for ssh?

**Comment by staticfloat** [comment]
Alright, I got past it.  Thanks!

**Comment by tkelman** [comment]
What wound up being the issue?

**Comment by staticfloat** [comment]
I had tried to remove `/bin/cmake.exe` to force it to use `/usr/bin/cmake.exe`, but those two directories are the same under `cygwin`.  Orz

So I had to re-install `cmake` _and_ run it not via SSH, but through the cygwin shell.

**Comment by staticfloat** [comment]
@tkelman could you try out the [latest win64 binary](https://s3.amazonaws.com/julianightlies/bin/winnt/x64/0.4/julia-0.4.0-0f7dee9511-win64.exe) and ensure it's getting signed properly?  I think we may be back up and running on win64!

**Comment by tkelman** [comment]
Can't remember what my machine would do for an unsigned binary but I'll try and compare in a bit. The sign step appears to be successful, but the report success isn't?

**Comment by staticfloat** [comment]
Yeah, for some reason the windows builds can't make HTTPS connections to status.julialang.org.  Trying to figure it out, but it's bizarre.

**Comment by tkelman** [comment]
It used to work. How much is different between the old image and the new?

**Comment by staticfloat** [comment]
I'm using a windows server 2012 base instead of windows 8.1 pro, so
potentially a lot.

**Comment by tkelman** [comment]
Interesting, i wonder if this is related to https://github.com/JuliaLang/ZMQ.jl/issues/90#issuecomment-134346731 ?

Is it server 2012 R2? That should theoretically be pretty similar to windows 8 I would think, but I guess the default security settings are different?

**Comment by tkelman** [comment]
This was worked around by sending the status pings from the master rather than the buildslaves, good enough for me.
