### ISSUE TITLE
build.julialang.org should actually exist

### ISSUE THREAD

**Issue by tkelman** [staticfloat/julia-buildbot#35]
cc @stefankarpinski, along with cache.julialang.org, ref https://github.com/JuliaLang/WinRPM.jl/issues/57#issuecomment-150830473

**Comment by tkelman** [comment]
huzzah, it exists now, but has to use http://build.julialang.org:8010 - how do we get rid of the need for the `:8010` ?

**Comment by staticfloat** [comment]
[Done and done](https://build.julialang.org/).  Now available not only over port 80, but over HTTPS.

**Comment by tkelman** [comment]
yay, thanks! now if only I knew how to solve (or even locally reproduce) https://github.com/JuliaLang/julia/issues/9572 or https://github.com/JuliaLang/julia/issues/13719 which are afflicting the osx and centos buildbots

**Comment by staticfloat** [comment]
Agreed.  I have no idea why those things are happening.  Hopefully someone with enough time on their hands and the ability to track it down will get tired of not having nightlies and will fix it.  Alternatively, if someone wants to fix it but can't reproduce locally, I can grant temporary buildbot SSH access.
