### ISSUE TITLE
Signing failed due to no more space on .dmg

### ISSUE THREAD

**Issue by staticfloat** [staticfloat/julia-buildbot#38]
@one-more-minute your OSX [juno signing failed](http://buildbot.e.ip.saba.us:8010/builders/juno_osx10.9-x64/builds/4/steps/shell_1/logs/stdio)

```
error: /Library/Developer/CommandLineTools/usr/bin/codesign_allocate: can't write output file: /Volumes/Juno/Juno.app/Contents/Frameworks/ElectronFramework.framework/Versions/Current/Electron Framework.cstemp (No space left on device)
```

Looking at the .dmg, it doesn't have much space free.  Are you creating that .DMG file or am I?  It looks like it's created with a limit of 900 MB, perhaps try bumping that up to 1500MB, just to future-proof it?

**Comment by one-more-minute** [comment]
Alright, I've updated the DMG size. Is it safe to run the OS X signing bot again, or should I wait?

**Comment by staticfloat** [comment]
Go ahead and run it
