### ISSUE TITLE
Please upgrade to cmake 3.4.3+ on llvmsvn buildbot

### ISSUE THREAD

**Issue by yuyichao** [staticfloat/julia-buildbot#46]
LLVM recently switched to require cmake 3.4.3+ so we need to upgrade it on the buildbot (It was announced on llvm-dev a few month ahead but I didn't realized that we'll be affected...)

@staticfloat @tkelman

**Comment by tkelman** [comment]
I may have enough of the login info to do this manually, just download https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz then set `CMAKE` in `Make.user` to point to it. Don't bother trying to move it around or make symlinks to put it in `/usr/local`, you'll get complaints about `CMAKE_ROOT` not being set.

I'd rather avoid doing this manually though, it should be automated in the provisioning scripts. I don't know how those work or where all of them are. Something to do with ansible which I've never really touched apart from modifying a yml file once or twice.

**Comment by staticfloat** [comment]
I'm back from Mexico, this should be done now.

For reference, this is done by running something like `ansible-playbook -i hosts -v buildslaves.yml -l buildslave_ubuntu14.04-x86,buildslave_ubuntu14.04-x64` on `buildslaves.yml` from [this repository](https://github.com/staticfloat/julia-ansible-scripts).  Note that if you want to run this locally, you're gonna need some ansible roles such as this [buildslave role](https://github.com/staticfloat/ansible-julia_buildslave).

**Comment by staticfloat** [comment]
Wait, no, I didn't realize that I have to add a PPA for this.  Stand by.

**Comment by tkelman** [comment]
Is there a PPA that has 3.4.3 or newer?

**Comment by staticfloat** [comment]
Nope, we're [building and installing](https://github.com/staticfloat/julia-ansible-scripts/blob/a7dc9b1863032e15563c9ac3e476edf14884fa78/cmake_install.yml) it to `~/local` now.  This should be done now, although the location of `cmake` has changed, so not sure if we need to nuke the buildbots or not.
